export const CHANGE_SEARCH_VALUE = 'CHANGE_SEARCH_VALUE';
export const REQUEST_COINS_PENDING = 'REQUEST_COINS_PENDING';
export const REQUEST_COINS_SUCCESS = 'REQUEST_COINS_SUCCESS';
export const REQUEST_COINS_FAIL = 'REQUEST_COINS_FAIL';
export const REQUEST_PRICES_PENDING = 'REQUEST_PRICES_PENDING';
export const REQUEST_PRICES_SUCCESS = 'REQUEST_PRICES_SUCCESS';
export const REQUEST_PRICES_FAIL = 'REQUEST_PRICES_FAIL';