export const CHANGE_SEARCH_VALUE = 'CHANGE_SEARCH_VALUE';
export const REQUEST_COINS_PENDING = 'REQUEST_COINS_PENDING';
export const REQUEST_COINS_SUCCESS = 'REQUEST_COINS_SUCCESS';
export const REQUEST_COINS_FAIL = 'REQUEST_COINS_FAIL';